gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 2592000 # 30 días de duración del refresh token
    ttl_update: true # Renueva el tiempo de vida del refresh token cada vez que se usa
    token_parameter_name: refresh_token
    single_use: true

