security:
    encoders:
        App\Entity\User:
            algorithm: auto

    role_hierarchy:
<<<<<<< HEAD
        ROLE_LOGISTICS:   ROLE_USER
        ROLE_ADMIN:       ROLE_LOGISTICS
=======
        ROLE_CALENDAR_EDITOR: ROLE_USER
        ROLE_NEWS_EDITOR: ROLE_USER
        ROLE_LOGISTICS:   ROLE_USER
        ROLE_ADMIN:       [ROLE_LOGISTICS, ROLE_NEWS_EDITOR, ROLE_CALENDAR_EDITOR]
>>>>>>> 078628c (Calendar draft)
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        refresh_token_provider:
            id: gesdinet.jwtrefreshtoken.user_provider


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_doc:
            pattern: ^/api/doc
            security: false
            
        refresh:
            pattern:  ^/api/token/refresh
            stateless: true
            anonymous: true
            user_checker: security.user_checker 
            provider: refresh_token_provider
            guard:

                authenticators:
                    - gesdinet.jwtrefreshtoken.authenticator

        login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            json_login:
                check_path: /api/login

                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            anonymous: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            guard:

                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            lazy: true
            anonymous: true
            provider: app_user_provider

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [OPTIONS] }
        
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register, roles: ROLE_ADMIN }
        - { path: ^/api/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/reset-password, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/users, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/products, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/chat, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/board, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
